### PR TITLE
Added skip links to index page

### PR DESCRIPTION
**Pull request by clivecharles**

### CODE REVIEW

**Review by qasimwarraich — APPROVED** [review]
This looks good but shouldn't the visibility be set to hidden somewhere?

**Review by qasimwarraich — CHANGES_REQUESTED** [review]
Visibility

**Comment by clivecharles** [comment]
Its in the index.css file

**Review by mariab19 — COMMENTED** [review]
Also news and events should probably have its own id and we should be able to see that the skip links of article 1 untile article 3 are contained in the news and events skip link

**Review by qasimwarraich — APPROVED** [review]

**Pull request merged**
